vatpac-technology/sops

- docs/stylesheets/extra.css
- docs/stylesheets/navigation.css
- mkdocs.yml
- overrides/assets/stylesheets/home.css
Updating styling to match home.vatpac.org colours.
> Theming testing

- docs/stylesheets/admonitions.css
- docs/stylesheets/extra.css
- docs/stylesheets/navigation.css
> Styling dev

- docs/assist-us/TODO.md
- docs/stylesheets/navigation.css
- Remove Previous/next navigation from the footer
- Add a permanent shadow to the navbar to improve visibility
- Change nav link bottom border colour to a darker grey and adjust hover effect to a dull blue.
> Minor Styling Fixes

- docs/controller-skills/classdtwr.md
- docs/controller-skills/vatsys.md
- fixed class d tower link
- updated preferred TCU/TWR windows displayed
> minor fixes

- docs/controller-skills/atis.md
Added VATSYS ATIS abbreviations list from old website
> ATIS Abbreviations

- docs/aerodromes/Melbourne.md
- docs/aerodromes/sydney.md
- docs/terminal/melbourne.md
Added more notes for TWR controllers to handle Sunbury Corridor and standardised presentation of standard assignable headings.
> Melbourne Sunbury Corridor & standardisation

- docs/controller-skills/CircuitOperations.md
I noticed a lot of tower controllers (not the least myself!) struggling with understanding circuit operations and especially what they can and can't do to separate / segregate traffic (especially in the absence of an overlying TMA controller). My hope with this page is to help S2 controllers such as myself to deal with VFR and circuit operations in a realistic, yet practical way.
I tried to summarise relevant techniques and phraseology from the existing VATPAC SOPS, the VATPAC Academy, MATS, and ERSA.
I'd appreciate any and all feedback 🙂
> Add Circuit Operations page

- docs/controller-skills/.pages
- docs/controller-skills/index.md
> I think I've broken it but lets see how it goes

- docs/aerodromes/Melbourne.md
- docs/terminal/melbourne.md
- Update airways clearance example on ML TCU page of MB closed after discussion with Alex
- Add note referencing ATIS heading to ML TWR Runway Modes section after student described confusion looking for that info
> Melbourne Notes & Example

- docs/controller-skills/sepstandards.md
- includes/abbreviations.md
> Improve wording of sep standards

- docs/aerodromes/Avalon.md
- docs/aerodromes/Cairns.md
- docs/aerodromes/Essendon.md
- docs/aerodromes/Melbourne.md
- docs/aerodromes/Perth.md
- docs/aerodromes/sunshinecoast.md
- docs/aerodromes/sydney.md
- docs/enroute/Brisbane Centre/ARL.md
- docs/enroute/Brisbane Centre/INL.md
- docs/enroute/Brisbane Centre/ISA.md
- docs/enroute/Brisbane Centre/KEN.md
- docs/enroute/Brisbane Centre/TRT.md
- docs/enroute/Melbourne Centre/ASP.md
- docs/enroute/Melbourne Centre/BIK.md
- docs/enroute/Melbourne Centre/ELW.md
- docs/enroute/Melbourne Centre/HUO.md
- docs/enroute/Melbourne Centre/OLW.md
- docs/enroute/Melbourne Centre/PIY.md
- docs/enroute/Melbourne Centre/TBD.md
- docs/enroute/Melbourne Centre/YWE.md
- docs/military/darwin.md
- docs/terminal/adelaide.md
- docs/terminal/brisbane.md
- docs/terminal/cairns.md
- docs/terminal/canberra.md
- docs/terminal/coral.md
- docs/terminal/melbourne.md
- docs/terminal/perth.md
- docs/terminal/sydney.md
- docs/terminal/tassie.md
Change to the display format of Coordination SOPs
**Changes**:
- Coordination Formatting (all pages)
> Update Coordination formatting

- .github/workflows/notify.yml
As mentioned in #183, further work was anticipated to update formatting. This PR adjusts newline interpreting to correct the formatting of messages. Image below shows the formatting using single quotes.
> Update notify.yml to fix message formatting

- docs/aerodromes/Amberley.md
- docs/enroute/Brisbane Centre/INL.md
- docs/terminal/amberleyoakey.md
- docs/terminal/brisbane.md
`Notify` tag not required. Just tidied up the page title and made a few formatting changes.
> Page title tidy up

- docs/aerodromes/Cairns.md
Change of the ATIS Formatting for Standardisation
**Fixes**:
- Change of the ATIS Formatting for Standardisation
> Cairns TWR.md

- docs/aerodromes/classc/Perth.md
- docs/controller-skills/cpdlc.md
- docs/enroute/Brisbane Centre/ISA.md
- docs/terminal/perth.md
Minor fixes
**Fixes**:
- Typos/Grammar in **CPDLC** page
- **Isa** Enroute Frequency now correctly shows as **125.7**
**Changes**:
- _MANDU_ renamed to **OLMAM** in 2406
> small fixes

- docs/enroute/Melbourne Centre/BIK.md
- docs/terminal/nowra.md
> Nowra Typo Fix

- overrides/assets/stylesheets/home.css
Fixes the menu not being shown between 1120px and 1220px wide.
**Fixes**:
- Fixes burger menu breakpoints
> fix menu breakpoint

- docs/client/maestro.md
**Fixes**:
- Grammatical & semantic errors on the Maestro page
> Semantic changes to Maestro

- mkdocs.yml
- requirements.txt
Adds lightbox ability to the website.
If the user clicks on the photo it shows a lightbox with the ability for the user to use arrows on the edge of the screen to change between photos.
**Changes**:
- Add a lightbox
> Add glightbox functionality to allow zooming of the photos

- docs/aerodromes/classc/Sydney.md
Made changes to the SOPs for the 2409 Cycle
**Changes**:
- Changed KAMPI to GROOK in all pages.
> 2409-Changes

- docs/terminal/adelaide.md
- docs/terminal/melbourne.md
Addition of Melbourne TCU Flow Data
**Additions**:
- **Melbourne TCU** Flow Data table
- Added note regarding *cumulative adjustments* to **Adelaide TCU** Flow Data Table
> ML TCU Flow Data

- docs/client/cpdlc.md
- docs/terminal/cairns.md
Fixes a handful of typos. `Notify` tag not required.
> Typo fixes

- docs/controller-skills/milkrun.md
Quick fix, no details required
> Update non-standard SY SMC position

- docs/worldflight/Aerodromes/adelaide.md
- docs/worldflight/Aerodromes/brisbane.md
- docs/worldflight/Aerodromes/darwin.md
- docs/worldflight/Aerodromes/perth.md
- docs/worldflight/Aerodromes/portmoresby.md
- docs/worldflight/Aerodromes/sydneydep.md
Quick typo fix, no `notify` required.
> Replace OzStrips ordering typo

- docs/pacific/Papua-New-Guinea/.pages
- docs/pacific/Papua-New-Guinea/Port Moresby (AYPY)/AD.md
- docs/pacific/Papua-New-Guinea/Port Moresby (AYPY)/TCU.md
Ordered PNG pages to keep AYPY pages at the top and together.
Added pages so that the index goes Enroute -> Moresby TCU -> Moresby -> Other Airfields, to prevent the TXU and Moresby pages from being separate in the list.
**Additions**:
- .pages
> Categorise AYPY SOPs

- docs/aerodromes/classd/Parafield.md
Fixes a typo regarding the VFR inbound procedures table for point OHB at YPPF.
**Fixes**:
- YPPF approach points table typo
> Fix YPPF Typo

- docs/aerodromes/classc/Sydney.md
- docs/terminal/adelaide.md
- docs/terminal/sydney.md
- mkdocs.yml
Added Content Tabs to improve formatting of Flow Tables and SID Selection Tables
**Changes**:
- Changed formatting of _Flow Tables_ at:
- **Adelaide TCU**
- **Sydney TCU**
- Changed formatting of **YSSY** _SID Selection_ Table
> Content Tabs

- docs/aerodromes/classc/Amberley.md
> Another typo fix

- docs/client/towerstrips.md
Adds missing right mouse click on SID clickspot and more descriptive notes for some other fields. `Notify` tag not required.
> Update OzStrips Clickspots

- docs/aerodromes/classc/Gingin.md
Fixes a flagged typo. `Notify` not required.
> Gingin Typo Fix

- docs/terminal/sydney.md
Fix issue noticed by Josh 
switch SAS and SAN in table
> SAS-SAN ID fix

- docs/aerodromes/classd/Bankstown.md
Adds info about the manoeuvring area at YSBK and updates the formatting of several sections of the page to make it more readable.
**Fixes**:
- Page formatting
**Additions**:
-  SMC information regarding movement area.
> YSBK Manoeuvring Area

- docs/aerodromes/classc/Edinburgh.md
- docs/aerodromes/classc/Melbourne.md
- docs/aerodromes/classc/Richmond.md
- docs/aerodromes/classc/Tindal.md
- docs/pacific/Papua-New-Guinea/Enroute.md
Various miscellaneous formatting and spelling fixes
**Fixes**:
- Edinburgh Initial and Pitch Procedures Typo
- Tindal Initial and Pitch Operations Typo
- Melbourne Pushback Disconnect Points Formatting Fix
- Richmond Standard Assignable Level Formatting Fix
- PNG Enroute AYPM Airspace Image Directory 
**Removals**:
- Tindal Initial and Pitch Operations Phraselogy Example
> QOL Updates

- docs/oceanic/Positions/TSN.md
Fixed TSN freq as raised in #481 
**Fixes**:
Changed Sops freq to match vatsys and afv stated frequency
> TSN Subsector Frequency Update

- docs/enroute/Melbourne Centre/BLA.md
- docs/javascripts/table-indent.js
- docs/stylesheets/admonitions.css
- docs/stylesheets/extra.css
- mkdocs.yml
**Fixes**:
- Fixed incorrect 'Eildon Weir' label in Benalla airspace diagram
**Changes**:
- Indentation added to different header/paragraph levels, to enable better readability
**Removals**:
- Removed unused admonition styling
> Header/Paragraph Indentation

- .github/workflows/ci.yml
- .github/workflows/pr.yml
Update so that our docs are validated as part of the PR.
**Changes**:
- Update version of steps in github actions to the latest
**Additions**:
- Validate PRs to make sure the images/links all lead to valid destinations.
> Add PR validation of mkdocs

- docs/aerodromes/procedural/Tamworth.md
**Fixes**:
- Minor fix to change reference from TW ADC 2 to TW ADC South
> Fix reference to ADC 2 -> ADC S Tamworth

- docs/terminal/sydney.md
Quick fix, `notify` not required.
> Fix wrong feeder fix

- docs/assist-us/.pages
- docs/assist-us/best-practices.md
- docs/assist-us/buildingblocks.md
- docs/assist-us/changes.md
- docs/assist-us/setup.md
- docs/assist-us/tips.md
Removes unused section in initial setup page, adds git as a dependency and provides advice on fixing an error. Orders Contribute section pages to provide more guidance to new users.
`Notify` not required
> Update Contribute section

- docs/controller-skills/military.md
Adds various notes to allow controllers to effectively handle military aircraft in a variety of airspace types.
**Changes**:
- Initial and Pitch phraseology
**Additions**:
- Handling military aircraft in formations individually
- Gear down check for military aircraft prior to landing
> Handling Military Aircraft

- docs/pacific/New-Caledonia/.pages
- docs/pacific/Vanuatu/.pages
Fixes broken fix in New Caledonia menu.
Reorders Vanuatu
> .pages fix
