vatpac-technology/sops

docs/aerodromes/Albury.md
docs/aerodromes/Coffs.md
docs/aerodromes/Hammo.md
docs/aerodromes/Hobart.md
docs/aerodromes/Launceston.md
docs/aerodromes/tamworth.md
docs/terminal/sydney.md
overrides/home.html

Received feedback that the Level Assignment section was being confused with standard assignable levels from ENR to TMA, added note to clarify.  Fixed other wording items.

SY TCU clarifications

---

docs/aerodromes/Melbourne.md

Removed separate level for VFR and made it `A050` for all aircraft after recent discussion.

Update YMML Standard Assignable Level

---

docs/controller-skills/.pages
docs/enroute/Brisbane Centre/ARL.md
docs/enroute/Brisbane Centre/INL.md
docs/enroute/Brisbane Centre/ISA.md
docs/enroute/Brisbane Centre/KEN.md
docs/enroute/Brisbane Centre/TRT.md
docs/enroute/Melbourne Centre/ASP.md
docs/enroute/Melbourne Centre/ELW.md
docs/enroute/Melbourne Centre/OLW.md
docs/enroute/Melbourne Centre/PIY.md
docs/military/woomera.md
docs/terminal/brisbane.md
docs/terminal/perth.md

- further fixes to "unrestricted" phraseology (mainly ENR pages that were missing it)
- controller skills content manually ordered alphabetically
- completed TRT page
- completed OLW page
- multiple fixes to PIY
- general typos
- removed all references to woomera
- added hotline highlight format to overflier coord sections that were missing it
- changed PH std assignable to F240. if they own up to F245, itd be weird that the std assignable is F180. ill double check it though

OLW, TRT, misc fixes

---

docs/aerodromes/Melbourne.md

Added D-ATIS operational info and description, as per the Melbourne Tower Local Instructions (2021, Version 23, Section 12.1.2):
[Melbourne Tower Local Instructions (2021)](https://github.com/vatpac-technology/sops/files/11203630/Docs_3-4_FOI-21-37.pdf)

Add 09A/16D Operational Info

---

docs/terminal/sydney.md

Had some students recently vectoring huge circuits to comply with this paragraph. From my understanding, this existed for PRMs and since aircraft on adjacent approaches only require 1nm between them now, these huge circuits don't seem to be necessary. Added a general note requiring a separation standard until adjacent aircraft are established, then descent on the approach.
~~Can someone with the knowhow confirm that aircraft established on parallel approaches at SY only require 1nm lateral sep?~~
Edit: confirmed with Jake

Remove IAP vectoring distances/levels

---

docs/enroute/Brisbane Centre/ARL.md
docs/enroute/Melbourne Centre/BIK.md
docs/stylesheets/navigation.css
docs/terminal/adelaide.md
docs/terminal/sydney.md

- Stop table of contents making links above the active one grey
- Add notes to BIK, ARL and SY TMA regarding the use of each runway and STAR (and when to use the alternate one)
- Update ARL subsector responsibilities
- Fix broken links
- Adjust SY TMA upper limit to FL285

Table of Contents Colour, YSSY Sequencing Notes & Small Fixes

---

docs/controller-skills/extending.md
docs/enroute/Melbourne Centre/HUO.md
docs/terminal/coral.md
docs/terminal/tassie.md

- TAS TMA is an optional extension for S3 controllers, not a compulsory one (in line with Coral App)
- HUO can choose to extend top down to either YMHB, YMLT, both, or neither. If they extend top down, they are expected to cover the TMA airspace and the aerodrome itself (previously they could cover the airspace to A015 and leave SFC-A015 uncontrolled). If they choose not to extend top down to a TMA, the class C & D A085 and below becomes class G
- Other tidy ups
**Feel free to review PR but please don't merge content until after event tonight (Monday)**

Tassie top down & extension rules

---

docs/pacific/vanuatu.md

The Vanuatu page of the pacific sops state "During Port Vila hours of watch, Port Vila Tower provides ATS for the entire Port Vila Sector." 😰😰. Port Vila Tower only provides air traffic services for the Port Vila TMA: SFC-3500ft, and 3500ft-9500ft
The Port Vila Sector the SOPs reference is the Port Vila CTA (Class D) from 9500ft-FL245, which is serviced by Port Vila Centre when online. Otherwise, the CTA reverts to Class G and is serviced by Nadi Oceanic
I'm not sure if this is a change made to allow for more air traffic control service provided in the pacific due to a lack of controllers or if it was just a mistake made in writing the SOPs

Correct Port Vila Tower airspace definition

---

docs/controller-skills/annotations.md
docs/controller-skills/coordination.md
docs/controller-skills/maestro.md
docs/separation-standards/assurance.md
docs/separation-standards/classd.md
docs/separation-standards/index.md
docs/separation-standards/parallelapps.md
docs/terminal/brisbane.md
docs/terminal/sydney.md
includes/abbreviations.md

- Removal of BMN (Brisbane Finals) position
- Fixed broken links for BN TCU airspace diagrams
- Minor typos/formatting fixes throughout SOPs
- Minor expansions/clarifications in Sep Assurance, Parallel apps, Annotations pages

BMN position removal, other misc fixes

---

docs/aerodromes/sydney.md

Adjusted layout of page to match other class C aerodromes. Added notes on standard taxi instructions when SMC & ADC are both online.

Add YSSY 16L/34R taxi instructions

---

docs/aerodromes/sydney.md

Adds notes on the use of Sydney Coordinator and updates various procedures with specific notes for non-standard aerodrome positions.
**Changes**:
- Updated layout of *Runway Modes* section to improve navigation
**Additions**:
- Sydney Coordinator procedures
- Ownership of the Heliport with multiple ADC positions online
- Transferring taxiing aircraft between SMC frequencies when multiple SMC positions online

Coordinator + non-standard positions

---

docs/terminal/tassie.md

Added standard tracking route for arrivals via NUNPA to aid with CTA containment and TCU traffic flow when RWY 32L is in operation.
**Changes**:
- Tabulate routes via IRSOM and NUNPA
**Additions**:
- Add tracking route ELREL MLTSA for arrivals via NUNPA

LT TCU: Add tracking route for arrivals via NUNPA

---

docs/aerodromes/Adelaide.md
docs/terminal/adelaide.md

Expanded procedures and examples describing VFR coastal transit of the Adelaide CTR.
- Changed recommended procedure altitude
- Moved clearance limit responsibility from ADC to TCU
- Improved examples for both TCU and ADC

Expand YPAD coastal transit procedures

---

docs/aerodromes/Perth.md
docs/enroute/Melbourne Centre/OLW.md
docs/enroute/Melbourne Centre/PIY.md
docs/terminal/perth.md

Improved YPPH Aerodrome and Terminal procedures, including standardising layout of various pages and supplementing existing docs with more info/examples.
**Fixes**:
- Fixed PH TCU coordination heading (referencing TCU instead of ADC)
**Changes**:
- Adjusted display of PH TWR runway modes section
**Additions**:
- Victor 65 notes to PH TCU
- Coordination notes and example for VFR departures from YPPH to PH TCU
- Runway modes to PH TCU and ENR pages
- Airspace note to OLW page regarding YPKA Class E airspace

Improve PH procedures

---

docs/aerodromes/Adelaide.md
docs/enroute/Brisbane Centre/ARL.md
docs/enroute/Melbourne Centre/BIK.md
docs/military/williamtown.md
docs/terminal/adelaide.md

Various example updates and additional notes covering coastal transits of Adelaide, tower closed procedures for ARL, and use of the adjacent STAR in Sydney.
**Fixes**:
- Fixed Adelaide coastal flying examples to include clearance limit
**Additions**:
- Added radio phraseology examples to ARL and BIK demonstrating amended STAR
- Added WLM TCU closed notes to ARL

Various Fixes

---

docs/aerodromes/sydney.md
docs/controller-skills/runwaymanagement.md
docs/enroute/Brisbane Centre/INL.md

Expanded on Runway Change actions and Sydney runway selection criteria.
**Additions**:
- Actions for each position type to complete when conducting a runway configuration change
- Preferred runways for departures from YSSY via PEGSU and KAMBA
- Note on balancing departure runway for jets planned via WOL

Runway Changes & Sydney Runway Selection

---

docs/terminal/sydney.md

Added SY ADC -> SY TCU Standard Assignable level to the Sydney TCU page
**Fixes**:
- Added missing SY ADC -> SY TCU Standard Assignable level to the Sydney TCU page

SY ADC->TCU STD Assignable

---

docs/aerodromes/Bankstown.md
docs/terminal/adelaide.md
docs/terminal/cairns.md
docs/terminal/canberra.md
docs/terminal/coral.md
docs/terminal/melbourne.md
docs/terminal/perth.md
docs/terminal/sydney.md

Added all other missing ADC->TCU Standard Assignable levels on the TCU pages
**Fixes**:
- Added missing AD ADC -> AD TCU Standard Assignable level on AD TCU page
- Added missing CS ADC -> CS TCU Standard Assignable level on CS TCU page
- Added missing CB ADC -> CB TCU Standard Assignable level on CB TCU page
- Added missing MK ADC -> MK TCU Standard Assignable level on Coral TCU page
- Added missing RK ADC -> RK TCU Standard Assignable level on Coral TCU page
- Added missing AV ADC ->  ML TCU Standard Assignable level on ML TCU page
- Added missing BK ADC -> SY TCU Standard Assignable level on SY TCU page
- Added missing BK ADC -> SY TCU Frequency Transfer altitude on BK ADC page
**Changes**:
- Changed BK ADC -> SY TCU Standard Assignable level to `A030` (no RFL if lower)
- Changed BK ADC …

More Missing Standard Assignables

---

.github/workflows/notify.yml

As requested by ATS, this PR adds an action to send a notification to the #sop-updates Discord channel when completing PRs with the "notify" tag attached. Further work is likely necessary to improve the formatting, so this is only a functional prototype at this stage.

Setup draft Discord update notifications

---

docs/aerodromes/Cairns.md
docs/aerodromes/Hobart.md
docs/aerodromes/Launceston.md
docs/aerodromes/Perth.md
docs/aerodromes/sydney.md
docs/enroute/Brisbane Centre/KEN.md
docs/enroute/Melbourne Centre/PIY.md
docs/terminal/cairns.md
docs/terminal/perth.md
docs/terminal/sydney.md

Changes to SOPs, Waypoint names, Procedures for AIRAC 2312
**Fixes**:
- Moved BK ADC -> SY TCU to Departures Coordination section
- Minor typos in SY ADC page
**Changes**:
- Waypoint name changes
- POONA > MUNAR
- SWIFT > AKROM
- CONNI > SAPKO
- KEELS > OPEGA
- WAVES > IPMOR
- CLARK > RIBLI
- IRONS > MIKIS
- KAREN > VEKLO
- NOLAN > VIMAP
- YSSY SID Selection changes
- YMLT SID Selection changes

AIRAC 2312 (Do not merge until 30/11)

---

docs/enroute/Brisbane Centre/INL.md

Clarifies the operation of the Class C airspace above the YBSU CTR.
- Reworded description of Class C airspace 4,500ft and above on INL SOPs page

Clarify CTA above YBSU

---

docs/aerodromes/Canberra.md
docs/enroute/Brisbane Centre/INL.md
docs/terminal/canberra.md

Adds SOPs for handling helicopter operations in and out of the various hospitals and helicopter bases in the Canberra CTR. Expands on YCFS tower closed procedures and clarifies airspace arrangement.
**Fixes**:
- Reworded INL coordination section to better reflect airspace arrangement
**Additions**:
- Added brief notes on INL handling YCFS departures with tower closed
- Added procedures for CB ADC and CB TCU to handle helicopter operations in the CB CTR

YSCB Helicopter Ops & YCFS Tower Closed Procedures

---

docs/enroute/Melbourne Centre/PIY.md
docs/terminal/perth.md

Adds notes on handling arrivals and departures via the unusual Class E FL125 CTA step south of YPPH.
**Additions**:
- PH TMA notes on runway mode in strong winds
- PH TMA notes on departures via the FL125 Class E CTA step to the south
- PIY notes on arrivals via the FL125 Class E CTA step to the south

Add Perth airspace notes

---

docs/aerodromes/Hobart.md
docs/aerodromes/Launceston.md

Added YMLT and YMHB ATIS Identifiers which differentiate themselves from the adjacent aerodrome.
**Additions**:
- YMLT and YMHB ATIS section
- YMLT utilizing A through M, YMHB utilizing N through Y.

Add Launceston and Hobart ATIS Identifier Restrictions

---

docs/aerodromes/classc/Brisbane.md
docs/terminal/tassie.md

Expands the standard taxi routes at Brisbane, including standard hold short instructions when transferring aircraft to neighbouring SMC frequencies and common conflict points between arriving and departing aircraft.
**Fixes**:
- Fixed image link on Tassie TCU page
**Additions**:
- Added additional notes on the standard taxi routes at Brisbane

Expand Brisbane Standard Taxi Routes

---

docs/enroute/Melbourne Centre/ELW.md

Change to CB TCU Offline Airspace Reclassification for ELW.
**Changes**:
- When CB TCU is Offline, and ELW is not providing top-down, only SFC-**A085** reverts to Class G (was SFC-F245)

ELW/CB TCU Reclassification

---

docs/controller-skills/airwork.md
docs/controller-skills/milkrun.md
docs/controller-skills/vatsys.md
docs/enroute/Brisbane Centre/ISA.md
docs/enroute/Melbourne Centre/ASP.md
docs/oceanic/index.md
docs/separation-standards/procedural.md
docs/stylesheets/navigation.css
docs/terminal/adelaide.md
docs/terminal/brisbane.md
docs/terminal/cairns.md
docs/terminal/canberra.md
docs/terminal/perth.md
docs/terminal/sydney.md
docs/terminal/williamtown.md
includes/abbreviations.md
mkdocs.yml

Addition of an Estimated Flow time table to the Sydney TCU page. Also, many other minor changes
**Fixes**:
- Links to Policies on various pages now open in new tab
- Fixed outdated link to Pacific Oceanic Agreement in Oceanic Overview page
**Changes**:
- Extendable Sections in various pages to reduce clutter, including:
- Sydney TCU
- Airwork / Special Operations
- vatSys Setup
- Milk Run Monday
- Procedural Separation Standards
- Updated MkDocs to latest version
**Additions**:
- Flow Table to Sydney TCU Page
- Abbreviations for MX and CSR

SY TCU Flow times, other minor fixes

---

docs/oceanic/index.md

Adds the Fukuoka FIR to the Oceanic page along with other minor corrections. https://github.com/vatpac-technology/sops/issues/236
**Fixes**:
Fixes section that says COL is still a subsector of TSN.
**Changes**:
Changes the information about Oakland Oceanic to reflect that it is owned and operated by the Oakland ARTCC. 
**Additions**:
Adds the Fukuoka Oceanic FIR.
Sources for Fukuoka:
https://www.mlit.go.jp/en/koku/content/001420936.pdf 
https://vatjpn.org/document/public/crc [Had use a translator]

Add Fukuoka to Oceanic & Fixes

---

.github/workflows/ci.yml
requirements.txt

Updated the pip requirements file to remove the pinned version for `mkdocs-material`. This change will resolve the CI error shown below when trying to deploy to GH pages.
An update to `mkdocs-material` caused the namespace for the emoji extension to change, and a mismatch of package versions between development and production environments meant that this was only occurring when building for release.

Fix failing CI job with old package version

---

docs/aerodromes/classc/Sydney.md
docs/aerodromes/classd/Hobart.md
docs/aerodromes/classd/Launceston.md
docs/enroute/Brisbane Centre/TRT.md
docs/enroute/Melbourne Centre/ASP.md
docs/enroute/Melbourne Centre/TBD.md
docs/terminal/adelaide.md
docs/terminal/cairns.md
docs/terminal/sydney.md
docs/terminal/tassie.md

Changes to AD and CS TCU positions, addition of YPAD Flow times, and more
**Fixes**:
- Fixed formatting and missing duplicated *Auto-Release* instructions between **SY ADC** and **SY TCU**
- Clarified that *Auto-Release* is **not available** for any *Jets departing 16L via WOL*
- Removed references to **HB and LT ACD** (Position does not exist) 
- Fixed missing **AS CTR** heading in *Reclassification* section of **ASP** page
**Changes**:
- *Standard Assignable level* from **HB and LT ADC** to **LTA/HBA** now changes based on *Flight Rules*, rather than *Jet/Non-Jet*
- *AAE* now Primary position in **AD TCU**, login identifier is now *AD_APP*, Callsign is now *"Adelaide Approach"*
- *AAW* login identifier now *AD-W_APP*
- *CS2* login identifier now *CS-W_APP*, Callsign is now *"Cairns …

AIRAC 2405

---

docs/separation-standards/runway.md
docs/separation-standards/surveillance.md
docs/separation-standards/visual.md
docs/separation-standards/waketurb.md
includes/abbreviations.md

Introduction of more detailed Wake Turbulence Separation Standards
**Additions**:
- **MTOW** Abbreviation
- Consolidated Wake Turbulence info from _Runway_ and _Surveillance_ pages in to a new **Wake Turbulence** page, with the addition of standards for:
- Airspace
- Arrivals
- Departures
- Crossing Runways
- Exceptions

Wake Turbulence Separation Standards

---

docs/aerodromes/classc/Sydney.md

Sydney YSSY is not an INTAS-equipped aerodrome and as such does not abbreviate 'instrument' to 'INST' in the ATIS (like Melbourne or Brisbane), rather instrument becomes 'INSTR'. This fix ensures correct information regarding the Sydney ATIS is reflected in the SOPs.
**Fixes**:
- Replaced 'INST' abbreviations with 'INSTR' for the Sydney (YSSY) ATIS section.

Added the correct ATIS abbreviation for 'instrument' at Sydney YSSY

---

docs/aerodromes/classc/Nowra.md
docs/terminal/nowra.md

Change YSNW standard assignable level from NW ADC to TCU from `A050` to `F120` to facilitate high performance aircraft with minimal operational impact.
**Changes**:
- Standard assignable level from NW ADC to TCU

Adjust YSNW Standard Assignable Level

---

docs/aerodromes/classc/Melbourne.md

Adjust ML 27AD/34D Runway Mode and Off Mode Departures
**Changes**:
- Updated 27AD/34D 
>`27 FOR ARR, RWY 34 FOR DEPS VIA MNG, NONIX, DOSEL AND BOGES, RWY 27 FOR ALL OTHER DEPS`
- Changed wording of RWY 16 Off Mode Departures to be more concise 
**Removals**:
- Removed reference to `Departures North-East`

Adjust ML 27AD/34D Runway Mode and Off Mode Departures

---

docs/enroute/Brisbane Centre/ARL.md
docs/enroute/Brisbane Centre/INL.md
docs/enroute/Brisbane Centre/KEN.md
docs/enroute/Brisbane Centre/TRT.md
docs/enroute/Melbourne Centre/ASP.md
docs/enroute/Melbourne Centre/ELW.md
docs/enroute/Melbourne Centre/HUO.md
docs/enroute/Melbourne Centre/OLW.md
docs/enroute/Melbourne Centre/PIY.md
docs/enroute/Melbourne Centre/TBD.md
docs/enroute/Melbourne Centre/YWE.md
docs/terminal/brisbane.md
docs/terminal/coral.md
docs/terminal/melbourne.md

Adds notes to specific enroute positions to suggest they publish an ATIS Zulu (Tower closed ATIS message) for particular aerodromes when choosing not to extend top down to those locations. This allows pilots to clearly understand the airspace reclassification and plan accordingly. The *More ATIS* plugin has pre-formatted Zulu messages for these locations.
**Fixes**:
- Enroute page CPDLC note format
**Additions**:
- ATIS Zulu messages to enroute pages when not extending top down to particular aerodromes

Add ATIS Zulu messages

---

docs/enroute/Brisbane Centre/ARL.md
docs/enroute/Brisbane Centre/KEN.md
docs/enroute/Melbourne Centre/BIK.md
docs/enroute/Melbourne Centre/ELW.md
docs/enroute/Melbourne Centre/PIY.md
docs/enroute/Melbourne Centre/TBD.md

Added requirements to provide a **2 minute sequencing** for aircraft assigned the **same runway**, through defined nearby **adjacent Feeder Fixes**
**Additions**:
- Subsequent arrivals through the following Feeder Fixes must be given a 2 minute sequence
- **Eildon Weir**
- **LIZZI** and **BOYSE** in to **YMML**
- Bindook
- **RIVET** and **ODALE** in to **YSSY**
- **LEECE** and **BUNGO** in to **YSCB**
- Armidale
- **BOREE** and **MEPIL** in to **YSSY**
- Pingelly
- **JULIM** and **SAPKO** in to **YPPH**
- Kennedy
- **ANDOP** and **PUNIT** in to **YBCS**
- **OVLET**, **AVDAN** and **LOCKA** in to **YBCS**
- Tailem Bend
- **MARGO** and **AGROS** in to **YPAD**
- **ERITH** and **KLAVA** in to **YPAD**

Sequencing through Adjacent Feeder Fixes

---

docs/aerodromes/classd/Bankstown.md
docs/client/cpdlc.md

Includes some semantic changes to CPDLC for clarity, along with some minor formatting changes to YSBK SOPs.
I did re-order the vatACARs instructions to be more appropriate; controllers must add PDC {ICAO} / CPDLC {ICAO} to their remarks before attempting to connect to vatACARs (the program will not identify a station code unless this is in the remarks). Previous SOPs had connection to vatACARs before adjusting remarks.
**Fixes**:
- Semantic changes to CPDLC for clarity
- Formatting changes to YSBK
**Changes**:
- Re-ordered vatACARs usage instructions to ensure controllers update remarks before attempting connection

Semantic Changes to CPDLC & YSBK Procedures

---

docs/enroute/Brisbane Centre/ARL.md
docs/enroute/Melbourne Centre/BIK.md
docs/enroute/Melbourne Centre/YWE.md
docs/terminal/melbourne.md
docs/terminal/sydney.md

**Additions**:
- **KAMBA** and **PEGSU** now available for Voiceless Coordination from **Sydney TCU** to **ARL** and **BIK** respectively
- **DOTPA**, **MENOG**, **OMKON** and **AV** now available for Voiceless Coordination from **Melbourne TCU** to **YWE**

Additional Voiceless Coord Routes

---

docs/enroute/Brisbane Centre/KEN.md
docs/terminal/townsville.md

Changes the standard handoff altitude for voiceless coordination from **KEN** to **TL TCU** from *A100* to *A090*, in line with actual procedure.
**Changes**:
- KEN -> TL TCU handoff altitude

Amend TL handoff altitude

---

docs/aerodromes/classc/Sydney.md

Changes the primary Sydney Ground position from SMC West to SMC East, to better reflect the type of traffic we generally encounter.
**Changes**:
- YSSY SMC default position

Update SY SMC default position

---

docs/client/towerstrips.md
docs/enroute/Brisbane Centre/ARL.md
docs/enroute/Brisbane Centre/INL.md
docs/enroute/Brisbane Centre/ISA.md
docs/enroute/Brisbane Centre/KEN.md
docs/enroute/Brisbane Centre/TRT.md
docs/enroute/Melbourne Centre/ASP.md
docs/enroute/Melbourne Centre/BIK.md
docs/enroute/Melbourne Centre/ELW.md
docs/enroute/Melbourne Centre/HUO.md
docs/enroute/Melbourne Centre/OLW.md
docs/enroute/Melbourne Centre/PIY.md
docs/oceanic/Positions/TSN.md

Updates requirements to handoff an aircraft to the VATNZ Oceanic sector. Adds examples of phraseology for domestic enroute sectors when handing aircraft to oceanic sectors. Adds keyboard shortcut notes to OzStrips workflow.
**Changes**:
- Requirement to establish aircraft at 10 minute longitudinal procedural separation  standard prior to handing off from HWE (surveillance) to Auckland Radio (procedural)
**Additions**:
- Phraseology examples to each domestic enroute sector when handing an aircraft to an oceanic sector
- Keyboard shortcut notes to OzStrips workflow for runway crossings

Oceanic Handoff Notes

---

docs/worldflight/Aerodromes/adelaide.md
docs/worldflight/Aerodromes/brisbane.md
docs/worldflight/Aerodromes/darwin.md
docs/worldflight/Aerodromes/perth.md
docs/worldflight/Aerodromes/portmoresby.md
docs/worldflight/Aerodromes/sydneydep.md

Clarifies particular procedures after recent community feedback. The use of the OzStrips plugin is mandatory for all aerodrome positions. Adds notes about the ordering of strips in an OzStrips bay.
**Additions**:
- OzStrips mandate note
- OzStrips ordering note

Add OzStrips Ordering & Mandate Notes

---

docs/terminal/sydney.md

DEENA SID no longer relevant to REP airspace considerations. GROOK SID height requirements assure aircraft are abv A100 before entering REP airspace over approach corridor.
**Removals**:
- Removed reference to DEENA SID in APP/DEP coordination section.

Remove REP reference to DEENA SID

---

docs/aerodromes/classc/Melbourne.md

Fixes a broken link on the Melbourne Aerodrome page pointing to the Milk Run Monday event SOPs.
**Fixes**:
- Link target on Melbourne Aerodrome page

Melbourne Aerodrome Broken Link Fix

---

docs/aerodromes/classc/Sydney.md

Minor amendment to remove mention of WOL transition for 16L ABBEY SID (it only goes to WOL).
**Fixes**:
- Minor amendment to 16L SID selection on YSSY page.

Update Sydney.md - Remove WOL from ABBEY SID

---

docs/separation-standards/assurance.md
docs/stylesheets/admonitions.css
mkdocs.yml

Fix Phraseology Admonition in Dark Mode

---

.github/workflows/notify.yml

Updates the GitHub Action publishing Discord notifications to run against code on the PR's base branch. This prevents issues around secret inaccessibility with changes from external authors or those with lower permission levels.
**Fixes**:
- Set action trigger to `pull_request_target` (instead of `pull_request`)

Run Discord notification job on base branch

---

docs/terminal/amberleyoakey.md
docs/terminal/darwin.md

Removes jurisdiction of the surrounding military SUA from Darwin TCU. The existing arrangement delegates airspace beyond the visibility range of the controller. This change removes that requirement and standardises the use of the airspace to match our implementation of other military aerodromes.
**Fixes**:
- BYRON7 departure initial constraint typo
**Removals**:
- DN TCU's jurisdiction of surrounding military SUA

Update YPDN TCU Jurisdiction

---

docs/aerodromes/classc/Sydney.md

Updates the Sydney heliport responsibility section to reference both runway 25 and runway 07 ops. SY ADC West is now responsible for managing helicopter operations when runway 07 is in use for arrivals or departures.
**Fixes**:
- Sydney heliport responsibility runway modes

Sydney Heliport Responsibility Update

---

.github/CODEOWNERS

This PR adds a `CODEOWNERS` file to automatically request a review from the `@vatpac-technology/sop-maintainers` team on new pull requests. Repository settings will also be updated to require an approving review from at least one designated codeowner following the merge of this PR.

Add CODEOWNERS support

---

docs/aerodromes/classc/Sydney.md

Improves the wording of the Sydney SID selection tables, to clarify that any pilot requiring the use of the Sydney Radar SID shall be assigned it, regardless of aircraft type.
**Fixes**:
- Sydney Aerodrome **Climb Gradient Requirements** section wording

Improve Sydney SID Selection Tables Wording

---

docs/terminal/melbourne.md

As raised by Nikola, AD TCU should have been ML TCU. `Notify` not required.
**Fixes**:
Should be ML not AD

ML TCU Typo

---

docs/aerodromes/classc/Perth.md
docs/aerodromes/classd/Jandakot.md
docs/enroute/Melbourne Centre/HYD.md
docs/terminal/perth.md

Clarifies the YPPH runway modes and standardises the display of information like ATIS elements. Standardises YPJT page to follow existing conventions.
`Notify` tag not required.

Minor Perth Refresh

---

.github/dependabot.yml

Introduce dependabot, a github feature which automatically updates the dependencies of projects. 
at the moment targetting npm/github-actions/pip
Just does weekly checks.
Noticed that the github actions were dramatically out of date, and dependabot is a free service by github for public repos
**Additions**:
- Add dependabot

Auto update dependencies

---

docs/stylesheets/navigation.css

**Fixes**:
- Removes the `height: -webkit-fill-available` property from the tab styles
Tested using Safari and Orion browsers. Checked compatibility on mobile too.

Fix navbar using full height on WebKit browsers

---

docs/aerodromes/classc/Essendon.md
docs/enroute/Melbourne Centre/HYD.md
docs/oceanic/Positions/IND.md

Removes GEL from the STAR Expectation list on the HYD Enroute page. Fixes a typo on the YMEN page.
**Fixes**:
- HYD page to remove reference to GEL STAR clearance issuance
- IND page to specify only LEA and JAR will provide STAR clearances for YPPH
- Essendon page typo fixes

Adjust HYD(GEL) STAR expectation, Essendon Typo fix

---

docs/enroute/Melbourne Centre/WOL.md
docs/pacific/Papua-New-Guinea/Enroute.md
docs/pacific/Papua-New-Guinea/Mt-Hagen.md
docs/pacific/Papua-New-Guinea/Nadzab.md
docs/pacific/Papua-New-Guinea/Tokua.md

Updates ATIS frequencies to match real world.
**Fixes**:
- Syncronises example of Class F overflier coordination across pages
**Changes**:
- Updates Tokua, Mt Hagen and Nadzab ATIS frequency per real world.

PNG Aerodrome ATIS frequency updates

---

overrides/home.html
overrides/main.html

Adds a noindex, nofollow and noarchive meta tag to to the base "main" template to hide these pages from Google Search Results.
Unlinks home from extending main to extending base, so that the home page remains index-able

Add Noindex tag to hide SOP subpages from search engine results

---

docs/pacific/Papua-New-Guinea/classf/Tokua.md

Was updated correctly in https://github.com/vatpac-technology/sops/pull/507
Change inadvertently undone in https://github.com/vatpac-technology/sops/pull/522
Correct is 128.3. Already updated on website + in pac profile

Fix Tokua ATIS freq

---

docs/stylesheets/navigation.css

Fixes the display of the active link in the primary menu bar on desktop in dark mode. Previously, the active link was a fixed colour, optimised for light mode but with too little contrast in dark mode. This PR sets it to the variable foreground colour which updates based on the current theme mode.
`Notify` not required.

Fix dark mode active link styling

---

docs/aerodromes/classc/Gingin.md

Adds GIG_GND to Gingin SOPs.
Already in Vatsys, already on website list.

Add missing GIG_GND position
